QS : QS Panel UI changes
SystemUI: Fix QS tile icon crash with unsupported drawable types

Some QS tiles reference drawables that are not supported by
Compose's painterResource (e.g. inset, layer-list, animated
drawables). This caused SystemUI to crash with:

    java.lang.IllegalArgumentException: Only VectorDrawables and
    rasterized asset types are supported ex. PNG, JPG, WEBP

Replace painterResource with rememberDrawablePainter so icons
fall back to Android's Drawable system, which supports a wider
range of types. This avoids crashes while preserving proper
centering and sizing.

Additionally, add missing qs_battery_saver_icon_off__1 drawables
to fix a crash in QSTileImpl.getInvisibleDrawable when attempting
to inflate unavailable XML resources.

Test: Manual - add/remove custom QS tiles with various drawable
types, enable/disable battery saver, verify no crash and correct
icon rendering
Bug: 394738023
Change-Id: Ixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Signed-off-by: rmp22 <195054967+rmp22@users.noreply.github.com>
Signed-off-by: darkphnx <dark.phnx12@gmail.com>
Signed-off-by: Trishiraj <gamerprince.exp@gmail.com>
Signed-off-by: str143 <alexfinhart@gmail.com>
Signed-off-by: Mr-0 <oldcrocs21@gmail.com>
Signed-off-by: ryzenforce990 <ryzenforce990@gmail.com>